"""
Django settings for emf_bus_tracking project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import json
from django_query_profiler.settings import *

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-6vcl)$f1-=xmg@5uop^=%c$@#p@n5bt-x@w*p(b7=#b1odb)58"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "celery",
    "colorfield",
    "corsheaders",
    "adminsortable2",
    "gtfs",
    "hafas",
    "kosmos",
    "darwin",
    "tracking",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_cprofile_middleware.middleware.ProfilerMiddleware",
]

ROOT_URLCONF = "emf_bus_tracking.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "emf_bus_tracking.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

USE_I18N = True
USE_TZ = True
TIME_ZONE = "UTC"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CELERY_RESULT_BACKEND = "rpc://"
CELERY_BEAT_SCHEDULE = {
    "gtfs-rt": {
        "task": "gtfs.gtfs_rt_tasks.generate_gtfs_rt",
        "schedule": 10,
    }
}

TRANSIT_CONFIG = {
    "agency_id": "EMF",
    "agency_name": "Transport for EMF",
    "agency_url": "https://bus.emf.camp",
}

GTFS_CONFIG = {
    "agency": {
        "lang": "en",
        "phone": None,
        "fare_url": None,
        "email": "contact@emfcamp.org",
    },
    "feed": {
        "publisher": {
            "name": "Q Misell",
            "url": "https://magicalcodewit.ch",
        },
        "lang": "en",
        "contact_email": "q@magicalcodewit.ch",
        "contact_url": None,
    }
}

GTFS_TO_HTML_DATA_PATH = BASE_DIR / "gtfs-to-html-data"
GTFS_TO_HTML_OUTPUT_PATH = BASE_DIR / "schedule"
GTFS_TO_HTML_DOCKER = "theenbyperor/emf-gtfs-to-html:1"

CORS_ALLOW_ALL_ORIGINS = True

with open(BASE_DIR / "secrets" / "os.json") as f:
    os_secrets = json.load(f)
with open(BASE_DIR / "secrets" / "darwin.json") as f:
    darwin_secrets = json.load(f)

DATA_UPLOAD_MAX_NUMBER_FIELDS = None
DATA_UPLOAD_MAX_MEMORY_SIZE = 26214400

OS_API_KEY = os_secrets["api_key"]

DARWIN_MESSAGING_HOST = darwin_secrets["host"]
DARWIN_MESSAGING_USERNAME = darwin_secrets["username"]
DARWIN_MESSAGING_PASSWORD = darwin_secrets["password"]
DARWIN_CLIENT_ID = darwin_secrets["client_id"]
DARWIN_S3_ACCESS_KEY = darwin_secrets["s3_access_key"]
DARWIN_S3_SECRET_KEY = darwin_secrets["s3_secret_key"]

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.memcached.PyMemcacheCache",
        "LOCATION": "localhost:11211",
    }
}