# Generated by Django 5.0.3 on 2024-03-09 23:13

import django.db.models.deletion
import kosmos.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tracking", "0013_remove_vehicle_tracker_alter_journey_vehicle_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tracker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[("track24", "Track24"), ("nal", "NAL Research")],
                        max_length=255,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "imei",
                    models.CharField(
                        max_length=15,
                        unique=True,
                        validators=[kosmos.models.validate_imei],
                        verbose_name="IEMI",
                    ),
                ),
                (
                    "aes_encryption_key",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        validators=[kosmos.models.validate_aes_key],
                        verbose_name="AES encryption key",
                    ),
                ),
                (
                    "aes_decryption_key",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        validators=[kosmos.models.validate_aes_key],
                        verbose_name="AES decryption key",
                    ),
                ),
                (
                    "vehicle",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracker",
                        to="tracking.vehicle",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["imei"], name="kosmos_trac_imei_5f0770_idx")
                ],
            },
        ),
    ]
