# Generated by Django 5.0.1 on 2024-01-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0004_alter_journey_direction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journeypoint",
            name="departure_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
