# Generated by Django 5.0.1 on 2024-01-25 22:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0006_shape_alter_journeypoint_journey_journey_shape_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("header", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("url", models.URLField(blank=True, null=True, verbose_name="URL")),
                (
                    "severity",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(2, "Info"), (3, "Warning"), (4, "Severe")],
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceAlertPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("start", models.DateTimeField(blank=True, null=True)),
                ("end", models.DateTimeField(blank=True, null=True)),
                (
                    "service_alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="tracking.servicealert",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceAlertSelector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "journey",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracking.journey",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracking.route",
                    ),
                ),
                (
                    "service_alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selectors",
                        to="tracking.servicealert",
                    ),
                ),
                (
                    "stop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracking.stop",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehiclePosition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="tracking.vehicle",
                    ),
                ),
            ],
        ),
    ]
