# Generated by Django 5.0.3 on 2024-03-05 12:31

import django.db.models.deletion
import tracking.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0008_servicealert_cause_servicealert_effect"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicleposition",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AddField(
            model_name="journey",
            name="real_time_state",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Planned"), (2, "Active"), (3, "Completed")], default=1
            ),
        ),
        migrations.AddField(
            model_name="journeypoint",
            name="estimated_arrival",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journeypoint",
            name="estimated_departure",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journeypoint",
            name="real_time_arrival",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journeypoint",
            name="real_time_departure",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicleposition",
            name="heading",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicleposition",
            name="update_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vehicleposition",
            name="velocity_ms",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="journey",
            name="forms_from",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forms_into",
                to="tracking.journey",
            ),
        ),
        migrations.AlterField(
            model_name="journey",
            name="shape",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="journeys",
                to="tracking.shape",
            ),
        ),
        migrations.CreateModel(
            name="Tracker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[("track24", "Track24"), ("nal", "NAL Research")],
                        max_length=255,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "imei",
                    models.CharField(
                        max_length=15,
                        unique=True,
                        validators=[tracking.models.validate_imei],
                    ),
                ),
                (
                    "aes_encryption_key",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        validators=[tracking.models.validate_aes_key],
                        verbose_name="AES encryption key",
                    ),
                ),
                (
                    "aes_decryption_key",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        validators=[tracking.models.validate_aes_key],
                        verbose_name="AES decryption key",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["imei"], name="tracking_tr_imei_2f4323_idx")
                ],
            },
        ),
        migrations.AddField(
            model_name="vehicle",
            name="tracker",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vehicle",
                to="tracking.tracker",
            ),
        ),
    ]
