# Generated by Django 5.0.3 on 2024-03-06 00:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0009_alter_vehicleposition_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shape",
            name="last_average_speed_update",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ShapePointAverageSpeed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("valid_monday", models.BooleanField(blank=True, default=False)),
                ("valid_tuesday", models.BooleanField(blank=True, default=False)),
                ("valid_wednesday", models.BooleanField(blank=True, default=False)),
                ("valid_thursday", models.BooleanField(blank=True, default=False)),
                ("valid_friday", models.BooleanField(blank=True, default=False)),
                ("valid_saturday", models.BooleanField(blank=True, default=False)),
                ("valid_sunday", models.BooleanField(blank=True, default=False)),
                ("validity_start_time", models.TimeField()),
                ("validity_end_time", models.TimeField()),
                ("speed_kmh", models.FloatField()),
                (
                    "point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="average_speeds",
                        to="tracking.shapepoint",
                    ),
                ),
            ],
        ),
    ]
