# Generated by Django 5.0.3 on 2024-03-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0010_shape_last_average_speed_update_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shapepoint",
            name="speed_limit_kmh",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
