# Generated by Django 5.0.3 on 2024-03-07 12:58

import tracking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0011_shapepoint_speed_limit_kmh"),
    ]

    operations = [
        migrations.AddField(
            model_name="journey",
            name="kalman_estimator_state",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="journey",
            name="real_time_state",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Planned"),
                    (2, "Active"),
                    (3, "Completed"),
                    (4, "Cancelled"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="imei",
            field=models.CharField(
                max_length=15,
                unique=True,
                validators=[tracking.models.validate_imei],
                verbose_name="IEMI",
            ),
        ),
    ]
