# Generated by Django 5.0.3 on 2024-03-09 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0012_journey_kalman_estimator_state_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="tracker",
        ),
        migrations.AlterField(
            model_name="journey",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="journeys",
                to="tracking.vehicle",
            ),
        ),
        migrations.DeleteModel(
            name="Tracker",
        ),
    ]
