# Generated by Django 5.0.3 on 2024-03-12 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0013_remove_vehicle_tracker_alter_journey_vehicle_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journey",
            options={"ordering": ["code"]},
        ),
        migrations.AlterUniqueTogether(
            name="journey",
            unique_together=set(),
        ),
        migrations.RemoveField(model_name="journeypoint", name="arrival_time"),
        migrations.AddField(
            model_name="journeypoint",
            name="arrival_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Scheduled arrival time (UTC)"
            ),
        ),
        migrations.RemoveField(model_name="journeypoint", name="departure_time"),
        migrations.AddField(
            model_name="journeypoint",
            name="departure_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Scheduled departure time (UTC)"
            ),
        ),
        migrations.RemoveField(model_name="journeypoint", name="estimated_arrival"),
        migrations.AddField(
            model_name="journeypoint",
            name="estimated_arrival",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Estimated arrival time (UTC)"
            ),
        ),
        migrations.RemoveField(model_name="journeypoint", name="estimated_departure"),
        migrations.AddField(
            model_name="journeypoint",
            name="estimated_departure",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Estimated departure time (UTC)"
            ),
        ),
        migrations.RemoveField(model_name="journeypoint", name="real_time_arrival"),
        migrations.AddField(
            model_name="journeypoint",
            name="real_time_arrival",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Real-time arrival time (UTC)"
            ),
        ),
        migrations.RemoveField(model_name="journeypoint", name="real_time_departure"),
        migrations.AddField(
            model_name="journeypoint",
            name="real_time_departure",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Real-time departure time (UTC)"
            ),
        ),
        migrations.AlterField(
            model_name="journeypoint",
            name="stop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journey_points",
                to="tracking.stop",
            ),
        ),
        migrations.RemoveField(
            model_name="journey",
            name="date",
        ),
    ]
