# Generated by Django 5.0.3 on 2024-03-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tracking",
            "0014_alter_journey_options_alter_journey_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="journeypoint",
            name="arrival_time",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Scheduled arrival time (UTC)",
            ),
        ),
        migrations.AlterField(
            model_name="journeypoint",
            name="departure_time",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Scheduled departure time (UTC)",
            ),
        ),
        migrations.AlterField(
            model_name="journeypoint",
            name="estimated_arrival",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Estimated arrival time (UTC)",
            ),
        ),
        migrations.AlterField(
            model_name="journeypoint",
            name="estimated_departure",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Estimated departure time (UTC)",
            ),
        ),
        migrations.AlterField(
            model_name="journeypoint",
            name="real_time_arrival",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Real-time arrival time (UTC)",
            ),
        ),
        migrations.AlterField(
            model_name="journeypoint",
            name="real_time_departure",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Real-time departure time (UTC)",
            ),
        ),
        migrations.AlterField(
            model_name="stop",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
