# Generated by Django 5.0.3 on 2024-03-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0016_shapepointaveragespeed_direction"),
    ]

    operations = [
        migrations.AddField(
            model_name="stop",
            name="internal_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="stop",
            name="code",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stop",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
