# Generated by Django 5.0.3 on 2024-03-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrainOperatingCompany",
            fields=[
                (
                    "code",
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=256)),
                ("website", models.URLField(blank=True, max_length=512, null=True)),
            ],
        ),
    ]
