# Generated by Django 5.0.3 on 2024-03-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("darwin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CancellationReason",
            fields=[
                ("code", models.IntegerField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="LateRunningReason",
            fields=[
                ("code", models.IntegerField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "tiploc",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
                ("crs", models.CharField(blank=True, max_length=3, null=True)),
                ("toc", models.CharField(blank=True, max_length=2, null=True)),
                ("name", models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
