# Generated by Django 5.0.3 on 2024-03-11 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("darwin", "0002_cancellationreason_laterunningreason_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="toc",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="darwin.trainoperatingcompany",
            ),
        ),
    ]
