# Generated by Django 5.0.3 on 2024-03-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("darwin", "0003_alter_location_toc"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitoredStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crs", models.CharField(max_length=3)),
            ],
        ),
    ]
