# Generated by Django 5.0.3 on 2024-03-11 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("darwin", "0004_monitoredstation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="toc",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="darwin.trainoperatingcompany",
                verbose_name="Train Operating Company",
            ),
        ),
        migrations.AlterField(
            model_name="monitoredstation",
            name="crs",
            field=models.CharField(
                max_length=3, verbose_name="CRS code (station identifier)"
            ),
        ),
        migrations.CreateModel(
            name="Journey",
            fields=[
                ("date", models.DateField()),
                ("cancel_reason_near", models.BooleanField(blank=True, default=False)),
                (
                    "rtti_unique_id",
                    models.CharField(
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                        verbose_name="RTTI Unique ID",
                    ),
                ),
                ("uid", models.CharField(max_length=6, verbose_name="UID")),
                (
                    "headcode",
                    models.CharField(max_length=4, verbose_name="Headcode (train ID)"),
                ),
                ("q_train", models.BooleanField(blank=True, default=False)),
                (
                    "cancel_location",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="darwin.location",
                    ),
                ),
                (
                    "cancel_reason",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="darwin.cancellationreason",
                    ),
                ),
                (
                    "toc",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="darwin.trainoperatingcompany",
                        verbose_name="Train Operating Company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JourneyStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="darwin.journey"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="darwin.location",
                    ),
                ),
            ],
        ),
    ]
