# Generated by Django 5.0.3 on 2024-03-11 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("darwin", "0005_alter_location_toc_alter_monitoredstation_crs_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journeystop",
            options={"ordering": ("order",)},
        ),
        migrations.AddField(
            model_name="journeystop",
            name="canceled",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="journeystop",
            name="order",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="journeystop",
            name="platform",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="journeystop",
            name="public_arrival",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journeystop",
            name="public_departure",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journeystop",
            name="use_false_destination",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="journeystop",
            name="working_arrival",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journeystop",
            name="working_departure",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="journeystop",
            name="journey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stops",
                to="darwin.journey",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="journeystop",
            unique_together={("journey", "location", "order")},
        ),
    ]
