# Generated by Django 5.0.3 on 2024-03-11 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("darwin", "0006_alter_journeystop_options_journeystop_canceled_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("message_id", models.IntegerField(primary_key=True, serialize=False)),
                ("message", models.TextField()),
                ("category", models.CharField(max_length=255)),
                ("severity", models.CharField(max_length=255)),
                ("supress_rtt", models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name="journeystop",
            old_name="platform",
            new_name="current_platform",
        ),
        migrations.RemoveField(
            model_name="journey",
            name="q_train",
        ),
        migrations.AddField(
            model_name="journey",
            name="activated",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name="journey",
            name="late_location",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="late_journeys",
                to="darwin.location",
            ),
        ),
        migrations.AddField(
            model_name="journey",
            name="late_reason",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="darwin.laterunningreason",
            ),
        ),
        migrations.AddField(
            model_name="journey",
            name="late_reason_near",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="journeystop",
            name="actual_arrival",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journeystop",
            name="actual_departure",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journeystop",
            name="destination",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="journeystop",
            name="estimated_arrival",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journeystop",
            name="estimated_departure",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journeystop",
            name="origin",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="journeystop",
            name="planned_platform",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="journeystop",
            name="platform_confirmed",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="journeystop",
            name="platform_suppressed",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="journeystop",
            name="supress",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="journeystop",
            name="unknown_delay_arrival",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="journeystop",
            name="unknown_delay_departure",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="journey",
            name="cancel_location",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="cancellation_journeys",
                to="darwin.location",
            ),
        ),
        migrations.CreateModel(
            name="MessageStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crs", models.CharField(max_length=3)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stations",
                        to="darwin.message",
                    ),
                ),
            ],
        ),
    ]
