# Generated by Django 5.0.3 on 2024-03-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("darwin", "0009_alter_journeystop_actual_arrival_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journey",
            name="category",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
