# Generated by Django 5.0.3 on 2024-03-12 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("darwin", "0010_journey_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="journeystop",
            old_name="canceled",
            new_name="cancelled",
        ),
    ]
