# Generated by Django 5.0.3 on 2024-03-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("darwin", "0011_rename_canceled_journeystop_cancelled"),
    ]

    operations = [
        migrations.CreateModel(
            name="WelshStationName",
            fields=[
                (
                    "crs",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
