# Generated by Django 5.0.3 on 2024-03-12 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("darwin", "0012_welshstationname"),
    ]

    operations = [
        migrations.CreateModel(
            name="WelshTrainOperatingCompanyName",
            fields=[
                (
                    "toc",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="darwin.trainoperatingcompany",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
