# Generated by Django 5.0.3 on 2024-03-12 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("darwin", "0013_welshtrainoperatingcompanyname"),
        (
            "tracking",
            "0014_alter_journey_options_alter_journey_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitoredstation",
            name="linked_stop",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="darwin_link",
                to="tracking.stop",
            ),
        ),
        migrations.AlterField(
            model_name="welshtrainoperatingcompanyname",
            name="toc",
            field=models.OneToOneField(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                primary_key=True,
                serialize=False,
                to="darwin.trainoperatingcompany",
            ),
        ),
    ]
