# Generated by Django 5.0.3 on 2024-03-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("darwin", "0016_alter_cancellationreason_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="supress_rtt",
            field=models.BooleanField(default=False, verbose_name="Suppress RTT"),
        ),
    ]
